/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 tennis_court.glb 
Author: RS (https://sketchfab.com/adithya19)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tennis-court-02fae7583fb447a484ee5b7c76bef0e6
Title: Tennis Court 🎾
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/tennis_court.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.001}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['line_marking_Material_#4_0'].geometry} material={materials.Material_4} position={[0, 4775.5, 0]} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['play_Material_#3_0'].geometry} material={materials.Material_3} position={[0, -2044.75, 0]} />
        </group>
        <group position={[193.968, 708.598, 42.412]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <group position={[-7349.852, 635.688, -368]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Layer0_Material_#20_0'].geometry} material={materials.Material_20} position={[952.818, 368, 635.688]} />
          </group>
          <group position={[-7349.852, 635.688, -368]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Layer0_Material_#20_0_1'].geometry} material={materials.Material_20} position={[13734.563, 363.037, 635.688]} />
          </group>
          <mesh geometry={nodes['Layer0_Material_#4_0'].geometry} material={materials.Material_4} position={[41.883, -27.552, -230.567]} />
          <mesh geometry={nodes['Layer0_Material_#19_0'].geometry} material={materials.Material_19} position={[-3.922, -1.431, 169.039]} />
        </group>
        <group position={[-9114.277, -3.69, -226.168]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.6}>
          <mesh geometry={nodes['Line001_Material_#23_0'].geometry} material={materials.Material_23} position={[-1291.389, 255.994, 0]} scale={1.281} />
          <mesh geometry={nodes['Line003_Material_#23_0'].geometry} material={materials.Material_23} position={[2082.866, -663.815, 0]} scale={1.281} />
        </group>
        <group position={[9510.695, -3.69, -173.013]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.6}>
          <mesh geometry={nodes['Line004_Material_#23_0'].geometry} material={materials.Material_23} position={[-1291.389, 255.994, 0]} scale={1.281} />
          <mesh geometry={nodes['Line005_Material_#23_0'].geometry} material={materials.Material_23} position={[2082.866, -663.815, 0]} scale={1.281} />
        </group>
        <mesh geometry={nodes['outer_Material_#2_0'].geometry} material={materials.Material_2} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Rectangle024_Material_#18_0'].geometry} material={materials.Material_18} position={[-0.016, -150, 0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Ellipse001_Material_#18_0'].geometry} material={materials.Material_18} position={[0.001, -0.022, 10.891]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Rectangle025_Material_#5_0'].geometry} material={materials.Material_5} position={[-0.016, -40.044, 0.011]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes['Object001_Material_#6_0'].geometry} material={materials.Material_6} position={[0.001, -0.022, 10.891]} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tennis_court.glb')
