/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ball.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Null_Subdivision_Surface_1.geometry} material={materials.Green} position={[-0.512, -0.069, -0.406]} scale={0.01} />
      <mesh geometry={nodes.Null_Subdivision_Surface_1_Subdivision_Surface_11_Subdi_a4e87b7.geometry} material={materials.Seam} position={[-0.512, -0.069, -0.406]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/ball.glb')
